# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 10s
  scrape_interval: 5s
  scrape_timeout: 3s

  external_labels:
    #environment: harry-ubuntu
    monitor: 'PromStack'

alerting:
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - mcloud-alertmanager.herokuapp.com:443


# scrape_configs:
#   - job_name: blackbox
#     metrics_path: /probe
#     params:
#       module:
#       - http_2xx
#     relabel_configs:
#     - source_labels:
#       - __address__
#       target_label: __param_target
#     - source_labels:
#       - __param_target
#       target_label: instance
#     - replacement: blackbox:9115
#       target_label: __address__
#     static_configs:
#     - targets:
#       - www.google.com
#       - www.facebook.com
#       - www.robustperception.io
#       - devconnected.com
#
#   - job_name: 'blackbox-new'
#     metrics_path: /probe
#     params:
#       module: [http_2xx]
#     file_sd_configs:
#       - files: ['/etc/prometheus/file_sd/blackbox_targets.yml']
#     relabel_configs:
#       - source_labels: [__address__]
#         regex: (.*)(:80)?
#         target_label: __param_target
#       - source_labels: [__param_target]
#         regex: (.*)
#         target_label: instance
#         replacement: ${1}
#       - source_labels: []
#         regex: .*
#         target_label: __address__
#         replacement: blackbox:9115

  - job_name: PromStack
    static_configs:
      - labels:
          env: monitoring
          #service: PromStack
        targets:
          - mcloud-alertmanager.herokuapp.com:443
          - mcloud-alertmanager.herokuapp.com:443
      # - grafana:3000

  # - job_name: node
  #   file_sd_configs:
  #   - files:
  #     - /app/configs/file_sd/node.yml
  #   basic_auth:
  #     username: Foo
  #     password: Bar



rule_files:
  - /app/configs/rules.d/*.yml
