---
groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
     summary: "Instance down - {{ $labels.host }} | {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
     description: "Instance down {{ $labels.host }}:`{{ $labels.instance }}` service may down of job `{{ $labels.job }}`. "
    # Labels - additional labels to be attached to the alert
    labels:
       severity: 'critical'

# - name: targets
#   rules:
#   - alert: monitor_service_down
#     expr: up == 0
#     for: 30s
#     labels:
#       severity: critical
#     annotations:
#       summary: "Monitor service non-operational"
#       description: "Service {{ $labels.instance }} is down."


- name: host
  rules:
    - alert: "Port_down"
      expr: net_response_result_code{result_type="connection_failed"} > 0
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "service down on {{ $labels.host }} port {{ $labels.port }}"
        description:  "`{{ $labels.result }}` on `{{ $labels.port }}`. Reported by instance `{{ $labels.instance }}` of job `{{ $labels.job }}`"
        runbook: "https://mywiki.com/ElasticacheCPUUtilisation"
        GeneratorURL: "https://mywiki.com/ElasticacheCPUUtilisation"
        dashboard: "https://mywiki.com/ElasticacheCPUUtilisation"
        link_url : "http://192.168.43.102:9090/new/alerts"
        ExternalURL : "http://192.168.43.102:9090/new/alerts"


    - alert: MEMORY_USED_80
      expr: mem_used_percent > 80
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "Memroy alert - {{ $labels.host }} | {{ $labels.instance }} is {{ humanize $value}}%"
        description: "Memory consumption `{{ humanize $value}}%` on `{{ $labels.host }}`[`{{ $labels.instance }}`] "

    - alert: MEMORY_USED_90
      expr: mem_used_percent > 90
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Memroy alert - {{ $labels.host }} | {{ $labels.instance }} is {{ humanize $value}}%"
        description: "Memory consumption `{{ humanize $value}}%` on `{{ $labels.host }}`[`{{ $labels.instance }}`] "

    - alert: DISK_USAGE_80
      expr: disk_used_percent{fstype=~"xfs|ext4|nfs4|cifs"} > 80
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: '{{$labels.path}} volume {{ humanize $value}}% Full On {{ $labels.host }} [{{$labels.instance}}]'
        description: "Disk Utilization[`{{$labels.path}}`] is `{{ humanize $value}}%` full on `{{ $labels.host }}` [`{{$labels.instance}}`]."

    - alert: DISK_USAGE_90
      expr: disk_used_percent{fstype=~"xfs|ext4|nfs4|cifs"} > 90
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: '{{$labels.path}} volume {{ humanize $value}}% Full On {{ $labels.host }} [{{$labels.instance}}]'
        description: "Disk Utilization[`{{$labels.path}}`] is `{{ humanize $value}}%` full on `{{ $labels.host }}` [`{{$labels.instance}}`]."

    - alert: VAULT_SERVICE_DOWN
      expr: systemd_units_sub_code{name="vault.service",sub!="running"} >= 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: '{{ $labels.host }} [{{$labels.instance}}]'
        description: "Vault Service is `{{$labels.sub}}` on `{{ $labels.host }}` [`{{$labels.instance}}`]."

    - alert: PROMETHEUS_SERVICE_DOWN
      expr: systemd_units_active_code{name="prometheus.service",sub!="running"} >= 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: '{{ $labels.host }} [{{$labels.instance}}]'
        description: "Prometheus Service is `{{$labels.sub}}` on `{{ $labels.host }}` [`{{$labels.instance}}`]."

    - alert: OPENRESTY_SERVICE_DOWN
      expr: systemd_units_active_code{name=~"openresty.service",sub!="running"} >= 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: '{{ $labels.host }} [{{$labels.instance}}]'
        description: "Openresty Service is `{{$labels.sub}}` on `{{ $labels.host }}` [`{{$labels.instance}}`]."

    - alert: WEBSITE_STATUS_CHECK
      expr: http_response_http_response_code{status_code!~"200|301|302"}
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: '{{ $labels.host }} [{{$labels.instance}}]| {{ $labels.server }}'
        description: "Failed to check site `{{$labels.server}}` status is `{{$labels.status_code}}` on `{{ $labels.host }}` [`{{$labels.instance}}`]."

    - alert: SSLCertExpiringSoon
      expr: round((probe_ssl_earliest_cert_expiry - time()) /  86400 ) < 60
      for: 10m
      labels:
        severity: warning
        monitoring: ssl
      annotations:
        summary: '{{ $labels.instance }} SSL Expiring in {{$value}} days'
        description: "SSL Certificate expiring in `{{$value}} days` for  `{{$labels.instance}}` domain."

#   - alert: high_cpu_load
#     expr: node_load1 > 1.5
#     for: 30s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Server under high load"
#       description: "Docker host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."
#
#   - alert: high_memory_load
#     expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
#     for: 30s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Server memory is almost full"
#       description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."
#
#   - alert: high_storage_load
#     expr: (node_filesystem_size_bytes{fstype="aufs"} - node_filesystem_free_bytes{fstype="aufs"}) / node_filesystem_size_bytes{fstype="aufs"}  * 100 > 85
#     for: 30s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Server storage is almost full"
#       description: "Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."
#
# - name: containers
#   rules:
#   - alert: jenkins_down
#     expr: absent(container_memory_usage_bytes{name="jenkins"})
#     for: 30s
#     labels:
#       severity: critical
#     annotations:
#       summary: "Jenkins down"
#       description: "Jenkins container is down for more than 30 seconds."
#
#   - alert: jenkins_high_cpu
#     expr: sum(rate(container_cpu_usage_seconds_total{name="jenkins"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
#     for: 30s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Jenkins high CPU usage"
#       description: "Jenkins CPU usage is {{ humanize $value}}%."
#
#   - alert: jenkins_high_memory
#     expr: sum(container_memory_usage_bytes{name="jenkins"}) > 1200000000
#     for: 30s
#     labels:
#       severity: warning
#     annotations:
#       summary: "Jenkins high memory usage"
#       description: "Jenkins memory consumption is at {{ humanize $value}}."
